import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import { siteConfig } from "@/config/site";
import { locales, type Locale } from "@/i18n/routing";

type PageKey = "home" | "about" | "services" | "contact";

/**
 * Builds per-page metadata plus the hreflang alternates that let search
 * engines pair the two language versions of the same page.
 */
export async function buildMetadata(
  locale: Locale,
  page: PageKey,
  path: string,
): Promise<Metadata> {
  const t = await getTranslations({ locale, namespace: `meta.${page}` });

  const href = (l: string) => `/${l}${path === "/" ? "" : path}`;
  const languages = Object.fromEntries(locales.map((l) => [l, href(l)]));

  // The card generated by `[locale]/opengraph-image.tsx`. It has to be named
  // here rather than left to the file convention: a child segment that
  // declares `openGraph` replaces the parent's whole object, so /about and
  // friends would otherwise ship with no image at all.
  const card = (route: "opengraph-image" | "twitter-image") => ({
    url: `/${locale}/${route}`,
    width: 1200,
    height: 630,
    alt: t("title"),
  });

  return {
    // The title is the largest line in a search result and the strongest
    // on-page ranking signal a marketing page has. It was previously the
    // company name on all four pages, which left every result looking
    // identical and let Google rewrite the titles itself.
    title: t("title"),
    description: t("description"),
    metadataBase: new URL(siteConfig.url),
    applicationName: siteConfig.name,
    alternates: {
      canonical: href(locale),
      languages: { ...languages, "x-default": href("en") },
    },
    openGraph: {
      title: t("title"),
      description: t("description"),
      url: href(locale),
      siteName: siteConfig.name,
      locale: locale === "th" ? "th_TH" : "en_US",
      // The other locale, so a share on a Thai feed can surface the Thai page.
      alternateLocale: locales
        .filter((l) => l !== locale)
        .map((l) => (l === "th" ? "th_TH" : "en_US")),
      type: "website",
      images: [card("opengraph-image")],
    },
    twitter: {
      card: "summary_large_image",
      title: t("title"),
      description: t("description"),
      images: [card("twitter-image")],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        // Defaults cap the snippet and force a thumbnail-sized preview; both
        // are opt-out, and a B2B result reads better with the full snippet.
        "max-snippet": -1,
        "max-image-preview": "large",
        "max-video-preview": -1,
      },
    },
  };
}
